server:
  port: 11115
  servlet:
    context-path: /cisdi-pms-job

spring:
  test: sayHello
  # 设置时区，以北京时间显示报错信息的时间（等）：
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
  application:
    name: cisdi-pms-job
  datasource:
    username: qygly
    password: Qygly@123456
    # 注意更改ip和db：
    # 测试：
    url: jdbc:mysql://121.5.65.165:3306/test?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    #演示：
#    url: jdbc:mysql://121.5.65.165:3306/demo?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    # 正式：
#    url: jdbc:mysql://124.222.58.152:3306/prod?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    loadbalancer:
      ribbon:
        # Ribbon处于维护模式，不要启用：
        enabled: false
    nacos:
      discovery:
        server-addr: 121.5.62.215:8848
        # 指明本机IP注册到nacos：
        # ip: 119.84.70.230
    #线程池
  task:
    execution:
      pool:
        max-size: 32
        core-size: 16
        keep-alive: 60
        queue-capacity: 2048
        thread-name-prefix: springThreadPool
        waitForTasksToCompleteOnShutdown: true

      # 定时任务1小时执行一次：
  scheduled:
    fixedDelayString: 3600000

# 自动登录qygly平台的设置：
qygly:
  ext-rest-helper:
    # 启用FeignClient：
    enable-feign-client: true
    # 启用FeignClient的配置：
    enable-feign-client-config: true
    # 启用登录保持：
    enable-login-keeper: true

    # 设置登录保持的相关信息：
    login-keeper:
      userCode: admin
      userMobile:
      userEmail:
      # 经RSA公钥加密后的用户密码：
      # 密码123456、验证码7890对应的密码：
      #正式
#      userPsd: Ldw58k5ZboUoLtaWVYsN6eC1dgkzlK/GQx0dICPqffh2rDliLsUH3pB08hz2rg3RWy0PjNNo0FMHw7xuHx8qzptfRe9oeEpZ1l2VcxEProUDU/IdFGEuFyonGhy8u5CMrqg5EfMTxVvA/K/SoCpjCw3+dAnA0Nj5ZCQVsz3iOho=
      #测试
      userPsd: c/ZSy1090v9uGKj2uzNYgaND/T/fnxCy3nOK8gXwM87DV5SBSPtSECq+DKN4x2aBbZT3KtyCBoxS0A06crd4EeUlprtDYrtTf6lS4HDDY3bhkBQznLtnTiSm840f6sFbqwoQ4TvlMshPPFyRkBcXJL0gut+xboLmjjX0wmmFWVQ=
      valiCodeReqKey: ABCDEFGHIJKLMNOPQRSTUVWXYZ123456
      valiCode: 7890
      orgCode: test
      keeperIntervalSeconds: 5
    feign-client:
      name:
        qygly-login: qygly-all
        qygly-dict: qygly-all
        qygly-data: qygly-all
        qygly-file: qygly-all

cisdi-pms-job:
  # 发送给真实用户：
  remind-real-user: false
  # true：开启   false：关闭
  sms-switch: false
  # 统一发送每个用户流程通知的数量定时任务corn
  sms-timing: 0 0 9 * * ?
  # 短信配置定时任务corn表达式
  sms-time-corn: 0 0 0 1 1 *
  # 短信配置定时任务开关  true：开启   false：关闭
  sms-time-switch: false


flylog:
  log_sent_mode: thrift
  flume_agent: 10.100.7.219:4143
  platform: gcxmxtxxxt
  application: web
  flume_batch_size: 1
  sink_batch_size: 1
  enabled: true
  ignore:
    static:
      res: css,html,js,jpg,png,bmp,faicon,gif,ico,woff,otf,svg,ttf,woff2,eot,json
  flume_data_path: E:/iflytek/dir/web


logging:
#  config: classpath:/log4j-info.xml
  level:
    root: info
    com.itcodai.course03.dao: trace

dealt_work_job:
  mq:
    #测试环境
    username: yazhoubayusercenter
    password: fb7614f9ed314a9285bc502dd24d3e2a
    broker: tcp://59.50.38.27:1663
    remind_add_topic: /api/v1/remind/add
    remind_read_topic: /api/v1/remind/read
  request:
    path: https://portal.test.yzbays.cn
  response:
    hearder_parame: A2VvMvqa9+swnBswZ/ZB+Vj2TiqCzv3ouY1/xymoAgU=
  callback_url: http://139.159.138.11:9090/pc/unifiedLogin?redirect=/pc/process&activeName=2
  app_name: "工程项目信息协同系统"
  app_id: 61efaced4141ed89deeecbdb
#  ture： 真实电话   false： 测试电话
  phone_switch: false
#  待办事项开关   true：开  false：关
  dealt_switch: false
#  待办事项测试数据开关(同时控制待办事项添加  待办事项消除)   true：开  false：关
  dealt_switch_test: false

# openOffice配置
jodconverter:
  local:
    enabled: true
    #openOffice:安装地址
    office-home: C:\Program Files (x86)\OpenOffice 4
    #    office-home: opt/openoffice4
    #每个进程可以处理的最大任务数
    max-tasks-per-process: 10
    #每个 JODConverter 处理线程使用的端口列表，以逗号分隔。 office实例数等于端口数，因为每个端口号将启动 1个 office 进程。
    port-numbers: 8303

# 历史数据
history-data:
  #合同文件路径前缀
  contract-path-prefix: C:\Users\11376\Desktop\合约模板\20230217
  #项目导入文件路径前缀
  prj-path-prefix: C:\Users\11376\Desktop\项目模板\20230224
  #请求地址(测试)
  requestPath: http://139.159.138.11:9090/qygly-api/qygly-gateway/qygly-file/uploadFile
  #文件上传参数
  sevId: "0099799190825106248"
  fileGroupAttCode: FILE_ID_FIVE
  erId: