spring:
  application:
    name: cisdi-pms-mq
  datasource:
    username: qygly
    password: Qygly@123456
    # 注意更改ip和db：
    url: jdbc:mysql://10.130.19.248:3306/prod?useSSL=false&serverTimezone=Asia/Shanghai
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 10.130.19.241
    port: 5672
    username: admin
    password: admin@1234
    virtual-host: qygly
    listener:
      simple:
        # 单个队列的并发消费者的最小数量：
        concurrency: 5
        # 单个队列的并发消费者的最大数量：
        max-concurrency: 10
  cloud:
    nacos:
      discovery:
        server-addr: 10.130.19.98:8848


server:
  port: 11117

mq-queue: qygly-wf-callback-queue-prod