spring:
  application:
    name: cisdi-pms-mq
  datasource:
    username: qygly
    password: Qygly@123456
    # 注意更改ip和db：
    url: jdbc:mysql://121.5.65.165:3306/test?useSSL=false&serverTimezone=Asia/Shanghai
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 121.5.71.89
    port: 5672
    username: admin
    password: admin@1234
    virtual-host: qygly
    listener:
      simple:
        # 单个队列的并发消费者的最小数量：
        concurrency: 3
        # 单个队列的并发消费者的最大数量：
        max-concurrency: 10

server:
  port: 11117
