server:
  port: 21111
  servlet:
    context-path: /cisdi-microservice

spring:
  datasource:
    username: qygly
    password: Qygly@123456
    # 注意更改ip和db：
    url: jdbc:mysql://120.27.147.220:3306/test?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #    单机启用host、port：
    host: localhost
    port: 6379
    #   单机、哨兵公用password、database：
    password: redis@1234
    #    企业管理云的REDIS库：
    database: 7
    #   哨兵使用sentinel.master、sentinel.nodes：
    #    sentinel:
    #      master:
    #      nodes:
    #   连接池：
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: 5s
        min-idle: 0
        time-between-eviction-runs: 60s
  cloud:
    loadbalancer:
      ribbon:
        # Ribbon处于维护模式，不要启用：
        enabled: false
    nacos:
      discovery:
        server-addr: localhost:8848
        # 指明本机IP注册到nacos：
        # ip: 119.84.70.230
  #        ip: 115.236.153.174

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin@1234
    virtual-host: qygly
    listener:
      simple:
        # 单个队列的并发消费者的最小数量：
        concurrency: 3
        # 单个队列的并发消费者的最大数量：
        max-concurrency: 10


qygly:
  ext-rest-helper:
    # 启用FeignClient：
    enable-feign-client: true
    # 启用FeignClient的配置：
    enable-feign-client-config: true
    # 启用登录保持：
    enable-login-keeper: true

    # 设置登录保持的相关信息：
    login-keeper:
      userCode: cloud_admin
      userMobile:
      userEmail:
      # 经RSA公钥加密后的用户密码：
      # 密码123456、验证码7890对应的密码：
      #正式
      #      userPsd: Ldw58k5ZboUoLtaWVYsN6eC1dgkzlK/GQx0dICPqffh2rDliLsUH3pB08hz2rg3RWy0PjNNo0FMHw7xuHx8qzptfRe9oeEpZ1l2VcxEProUDU/IdFGEuFyonGhy8u5CMrqg5EfMTxVvA/K/SoCpjCw3+dAnA0Nj5ZCQVsz3iOho=
      #测试
      userPsd: TVzD5Xhb1zg0Nh9cDTc3aAFq1mddYOTNHVaQ6Lg1rsUeailHxEAI1kn3fPvf94UzSwStD0U5xRqYVgdDZSIxvHhCAfOpAgamwRmtCPVX0r1Y3+c91ZcPX2BPRunA1ftudkY5GXf/JLmh3b2m7RVsklHR6LQhgFbJ8gcm5UMTGfw=
      valiCodeReqKey: ABCDEFGHIJKLMNOPQRSTUVWXYZ123456
      valiCode: 7890
      orgCode: test
      keeperIntervalSeconds: 5
    feign-client:
      name:
        qygly-login: qygly-all
        qygly-dict: qygly-all
        qygly-data: qygly-all
        qygly-file: qygly-all

mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.cisdi.cisdischeduler.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
