server:
  port: 11137

spring:
  # 设置时区，以北京时间显示报错信息的时间（等）：
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
  application:
    name: anhui-sso
  cloud:
    nacos:
      discovery:
        #正式
        #        server-addr: 10.130.19.98:8848
        #测试
        server-addr: localhost:8848
    #  redis:
    #    单机启用host、port：
    #    host: 124.222.58.152
    #    port: 6379
    #   单机、哨兵公用password、database：
    #    password: redis@1234
    #    企业管理云的REDIS库：
    #    database: 8
    #   哨兵使用sentinel.master、sentinel.nodes：
    #    sentinel:
    #      master:
    #      nodes:
    #   连接池：
#    jedis:
#      pool:
#        max-active: 200
#        max-idle: 10
#        max-wait: 5s
#        min-idle: 0
#        time-between-eviction-runs: 60s

logging:
  #  config: classpath:/log4j-info.xml
  level:
    root: info
    com.itcodai.course03.dao: trace

#安徽单点登录
ah:
  clientId: 20e25b82-bbe4-459f-af55-3275cfbed695
  secret: O5XR2WONusEdTbam4rNA9k3i3OVhTZ/zHdDRvRD83fI=
  loginUserUrl: http://61.190.89.72:8088/isso/rest/loginuser
  redirect:
    loginAppId: 1788848432084652032
    url: https://qygly.com/vue/

