server:
  port: 11145
  servlet:
    context-path: /cisdi-pms-wordToPdf

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
  application:
    name: demo-ext
  datasource:
    username: qygly
    password: Qygly@123456
    # 注意更改ip和db：
    url: jdbc:mysql://10.130.19.248:3306/prod?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    url: jdbc:mysql://121.5.65.165:3306/test?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

# openOffice配置
jodconverter:
  local:
    enabled: true
    #openOffice:安装地址
    #windows配置
#    office-home: C:\Program Files (x86)\OpenOffice 4
    # linux配置
#    office-home: /opt/openoffice4/program
    office-home: /opt/openoffice4
    #    office-home: opt/openoffice4
    #每个进程可以处理的最大任务数
    max-tasks-per-process: 10
    #每个 JODConverter 处理线程使用的端口列表，以逗号分隔。 office实例数等于端口数，因为每个端口号将启动 1个 office 进程。
    port-numbers: 8200
