server:
  port: 11145
  servlet:
    context-path: /cisdi-pms-wordToPdf

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
  application:
    name: demo-ext
  datasource:
    username: qygly
    password: Qygly@123456
    # 注意更改ip和db：
    url: jdbc:mysql://10.130.19.248:3306/prod?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    url: jdbc:mysql://121.5.65.165:3306/test?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.pms.cisdipmswordtopdf.model
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml

